language: scala
scala: 2.12.11
jdk: openjdk8
jobs:
  include:
  - if: tag IS present
  exclude:
  - if: tag IS blank
services:
  - docker
before_install:
  - bash ./.travis/checkTag.sh $TRAVIS_TAG
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - git clone https://github.com/snowplow/snowplow.git && cd snowplow/2-collectors/scala-stream-collector/ && git checkout scala_stream_collector/1.0.1 && sbt publishLocal && cd ../../..
deploy:
  on:
    tags: true
  skip_cleanup: true
  provider: script
  script: sbt docker:publish
env:
  global:
  # DOCKER_USERNAME
  - secure: RYSa/G9Oetuy+bpTbcAqV9B+xjoovnu6QtpfaYiBpo4/WVcg8UMNXpbXOTHFXcVbT9SPqObZWg07p7vtfWr2fwVfVVrV2IbA8k7iL9VSOPNZS8pgkyEl0HxelsDo49XDy57Y5XvkSEfAURkSXP9q+exotR9ajwifR4RMgI0vskZ+2riEaTWvMbi9z90tSXXSPQdFg8ba/JJuLQIzC8kB9GtFWbdjTE4YiSyjem7ABPLC02En43ol8l6ZOO4CHHklgq17Ry3+0rsA2nc70ERYzC0eAmTRJc8f8kMUWKWsMoOVeO8P8jsc8SrX62ZOuRm7uUFjcTY5VIhQQCvjN8ju3s/PYrKjz6Zie/sktgmQ1CKul6czyy8v7RP78SYDeBnBdQXywJMhyTkPfTPTnR0tOosvuLEQucCCG+s7x0N9vHZnLPa7Vk2KAm/+/oFF3z/rUfdfKx1gn+OISmYfeA1jC2IXOyJu5YW799wwPPP+guQ/G4AmcvcOVRlLa/y6YJkbmUpcwaVcOfX4Ngid8smEIUKGpN/+gu4/l8kaokVTG6BKr1s1jxoT/+Z39fxGqJD4/Ia9kkioNDIQ+Qt4Gqtb8+BCUDutt+PPjdvJhRgyx1fbOa8fdWLVWhJAapKsSbieaAVUPLfnQgtTQ6hQd6ABznYm/BT0/NSTVJ6oLt7S3Zo=
  # DOCKER_PASSWORD
  - secure: LGMeNDLGGpvcNw06nM5yxMybcn/H2P+qyW/SL5v63+yMYVWrLiz3MuxaIAIMa2CqD+XkfJ4GjGoQ0243F84NnShCPlP5cOhSi7d6u1HcexP+lS3bzJg5YtfmKEzltZybg8//7V0luwo5tPIoT2WMqwN/L6Ov4l50RT+M28rWef0G1ZRHBfhc6ORroF8KyCqYKpM4ar8Bk3uxxlcR951qQwQIfzCUkRwvKLXJSVCaLkMbpBLPRyevyj4vcGTmcLkuBRvYFCoYAWZDTROqaU38mJG88qernjhvBnpJVjG5m5siCD0BDn7pBFc/v06LGgZNz+NO5/J8nEeW54xiaFndYs+4WUmMQk2wGAPFWFNWuscVv32mwMPC8cwaaQxn4Ta2sMNxa2LeKoi1TwxzW6ZfUfMWudr7yNlpd13KDoKkGpLa75rMCvk9dftPkAfPq2hi7PcHWptRmnEN4sPXBv+zz/flDDB9YgPyCKwDN88DUJdIF9EetFLh07YcJJuLBM2uyr7Jqkp66nT3iN2bUti9xrxDqI1KwXGObssUe3bx1aCUNuLksigX1d3TPd3+xIdEPIegyJGJmCS/rU8+7LVRTSBYWGG6zni1/UbNnHE3zHIQkSrTwwC6UPK/847Lya8ubFQxb6A1EGOF4Ri3fKRxeiOpAaiDgxyc0uFJFDwAoM8=
